### ISSUE TITLE
My target is same, like chrome

### ISSUE THREAD

**Issue by emma-eva** [islonely/tigerlily#2]
I am also building text-based browser (like edbrowse) using vlang. 

With supports (server side):
JavaScript engine (5.1)
Html parser
Css parser
etc etc chrome like everything...

Will build same as real browser (both gui and cli)

We can build together if you want, I will share my contact details. Thanks!

**Comment by islonely** [comment]
Server side like a headless browser? If so, that's something I'm wanting as well. The long-term plan is to make a browser with a GUI. But that sounds tedious and time-consuming. Programming is just a hobby for me, so I won't be able to dedicate full-time hours to any project. And I've never formally done work as part of a team before. But having help for a project this big sounds nice :)

**Comment by emma-eva** [comment]
Yes headless browser, can be use ncurses gui like interface to run gui browser on Linux cli/terminal, later for windows/others os.

I built html and css parser, building now js engine. After build all of 80-90% I will show you then you can help me to upgrade in your part-time.

Also adding proxy support (http/s auth).
